### ISSUE TITLE
When a graph query has no arguments, I expect the `Ash.Query` object (as visible via the `prepare` function in the DSL) to have an empty map.

### ISSUE THREAD

**Issue by zorn** [ash-project/ash_graphql#89] opened 2023-08-15 23:24 UTC
I'm new to AshGraph, and while tinkering, I discovered an unexpected behavior where even when I do not define any arguments in the graph query the `Ash.Query` always contains the field name in the arguments map with a `nil` value. 

```graphql
    query {
      postScore {
        id
        score
      }
    }
```

And as seen while debugging in `prepare`...

```elixir
      prepare(fn query, _ ->
        dbg(query)
      end)
```

```elixir
query #=> #Ash.Query<
  resource: AshGraphql.Test.Post,
  arguments: %{score: nil},
  select: [:score, :id]
>
```

Some staging of the issue is here:

https://github.com/zorn/ash_graphql/commit/995e169deb125b76c6fedb1bc840b585d62d3b1c

This comes from a Discord discussion here:

https://discord.com/channels/711271361523351632/1141111863648731197/1141128943995457657

There it was suggested that the problem might be in `set_query_arguments/3`, but my initial introspection could not find an issue with that part of the code. It almost feels like the arguments are coming from somewhere else.

**Comment by zachdaniel** [comment] 2023-08-15 23:49
Wow, no wonder this was confusing! The problem isn't actually "real" 😆 . In our implementation of the inspect protocol, we inspect all argument values even ones that aren't set 🤦 . This issue will be fixed in Ash, so I'll close this one and make that change now. Good find :)

**Closed by zachdaniel** 2023-08-15 23:49 UTC
Labels: enhancement

**Comment by zorn** [comment] 2023-08-16 23:49
Thanks for the help and the fix!

**Comment by zorn** [comment] 2023-08-17 00:14
Linking the fix for prosperity: https://github.com/ash-project/ash/commit/46e8dd43bda259964f18128c3c774ae7385bb7e8
